sudo: false
language: java

dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

before_install: ant prepare-ivy
install: ant setup
script: ant -lib /home/travis/.ant/lib -lib /usr/share/ant/lib test
